export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD';
export const MOVIES_LOADING = 'MOVIES_LOADING';
export const MOVIES_FETCHED = 'MOVIES_FETCHED';
export const MOVIES_FAILED = 'MOVIES_FAILED';
export const BOOKS_LOADING = 'BOOKS_LOADING';
export const BOOKS_FETCHED = 'BOOKS_FETCHED';
export const BOOKS_FAILED = 'BOOKS_FAILED'; 